// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/chat_history.dart';
import 'models/document_chunk.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 3555535402585501559),
    name: 'DocumentChunk',
    lastPropertyId: const obx_int.IdUid(4, 3402132815190790762),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2162364415982130673),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7581979953479869495),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1856293770407682245),
        name: 'fileName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3402132815190790762),
        name: 'signature',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(1, 8644215214992636972),
        hnswParams: obx_int.ModelHnswParams(dimensions: 1536),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 2391369346006943837),
    name: 'ChatMessageEntity',
    lastPropertyId: const obx_int.IdUid(5, 8003212851453468315),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2078318489556208222),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1334439365793609827),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1640014571977757087),
        name: 'isUser',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1970915562416848669),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8003212851453468315),
        name: 'sessionId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(2, 808633648634762388),
        relationTarget: 'ChatSession',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 6406685179742239241),
    name: 'ChatSession',
    lastPropertyId: const obx_int.IdUid(3, 196643869565992661),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2798214147332270943),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 1101077580928428854),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 196643869565992661),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[
      obx_int.ModelBacklink(
        name: 'messages',
        srcEntity: 'ChatMessageEntity',
        srcField: 'session',
      ),
    ],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 6406685179742239241),
    lastIndexId: const obx_int.IdUid(2, 808633648634762388),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    DocumentChunk: obx_int.EntityDefinition<DocumentChunk>(
      model: _entities[0],
      toOneRelations: (DocumentChunk object) => [],
      toManyRelations: (DocumentChunk object) => {},
      getId: (DocumentChunk object) => object.id,
      setId: (DocumentChunk object, int id) {
        object.id = id;
      },
      objectToFB: (DocumentChunk object, fb.Builder fbb) {
        final textOffset = fbb.writeString(object.text);
        final fileNameOffset = fbb.writeString(object.fileName);
        final signatureOffset = object.signature == null
            ? null
            : fbb.writeListFloat32(object.signature!);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, textOffset);
        fbb.addOffset(2, fileNameOffset);
        fbb.addOffset(3, signatureOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final fileNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final signatureParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final object = DocumentChunk(
          text: textParam,
          fileName: fileNameParam,
          signature: signatureParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    ChatMessageEntity: obx_int.EntityDefinition<ChatMessageEntity>(
      model: _entities[1],
      toOneRelations: (ChatMessageEntity object) => [object.session],
      toManyRelations: (ChatMessageEntity object) => {},
      getId: (ChatMessageEntity object) => object.id,
      setId: (ChatMessageEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ChatMessageEntity object, fb.Builder fbb) {
        final textOffset = fbb.writeString(object.text);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, textOffset);
        fbb.addBool(2, object.isUser);
        fbb.addInt64(3, object.timestamp.millisecondsSinceEpoch);
        fbb.addInt64(4, object.session.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final isUserParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          8,
          false,
        );
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final object = ChatMessageEntity(
          text: textParam,
          isUser: isUserParam,
          timestamp: timestampParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        object.session.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        object.session.attach(store);
        return object;
      },
    ),
    ChatSession: obx_int.EntityDefinition<ChatSession>(
      model: _entities[2],
      toOneRelations: (ChatSession object) => [],
      toManyRelations: (ChatSession object) => {
        obx_int.RelInfo<ChatMessageEntity>.toOneBacklink(
          5,
          object.id,
          (ChatMessageEntity srcObject) => srcObject.session,
        ): object.messages,
      },
      getId: (ChatSession object) => object.id,
      setId: (ChatSession object, int id) {
        object.id = id;
      },
      objectToFB: (ChatSession object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, titleOffset);
        fbb.addInt64(2, object.timestamp.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final object = ChatSession(title: titleParam, timestamp: timestampParam)
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
        obx_int.InternalToManyAccess.setRelInfo<ChatSession>(
          object.messages,
          store,
          obx_int.RelInfo<ChatMessageEntity>.toOneBacklink(
            5,
            object.id,
            (ChatMessageEntity srcObject) => srcObject.session,
          ),
        );
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [DocumentChunk] entity fields to define ObjectBox queries.
class DocumentChunk_ {
  /// See [DocumentChunk.id].
  static final id = obx.QueryIntegerProperty<DocumentChunk>(
    _entities[0].properties[0],
  );

  /// See [DocumentChunk.text].
  static final text = obx.QueryStringProperty<DocumentChunk>(
    _entities[0].properties[1],
  );

  /// See [DocumentChunk.fileName].
  static final fileName = obx.QueryStringProperty<DocumentChunk>(
    _entities[0].properties[2],
  );

  /// See [DocumentChunk.signature].
  static final signature = obx.QueryHnswProperty<DocumentChunk>(
    _entities[0].properties[3],
  );
}

/// [ChatMessageEntity] entity fields to define ObjectBox queries.
class ChatMessageEntity_ {
  /// See [ChatMessageEntity.id].
  static final id = obx.QueryIntegerProperty<ChatMessageEntity>(
    _entities[1].properties[0],
  );

  /// See [ChatMessageEntity.text].
  static final text = obx.QueryStringProperty<ChatMessageEntity>(
    _entities[1].properties[1],
  );

  /// See [ChatMessageEntity.isUser].
  static final isUser = obx.QueryBooleanProperty<ChatMessageEntity>(
    _entities[1].properties[2],
  );

  /// See [ChatMessageEntity.timestamp].
  static final timestamp = obx.QueryDateProperty<ChatMessageEntity>(
    _entities[1].properties[3],
  );

  /// See [ChatMessageEntity.session].
  static final session = obx.QueryRelationToOne<ChatMessageEntity, ChatSession>(
    _entities[1].properties[4],
  );
}

/// [ChatSession] entity fields to define ObjectBox queries.
class ChatSession_ {
  /// See [ChatSession.id].
  static final id = obx.QueryIntegerProperty<ChatSession>(
    _entities[2].properties[0],
  );

  /// See [ChatSession.title].
  static final title = obx.QueryStringProperty<ChatSession>(
    _entities[2].properties[1],
  );

  /// See [ChatSession.timestamp].
  static final timestamp = obx.QueryDateProperty<ChatSession>(
    _entities[2].properties[2],
  );

  /// see [ChatSession.messages]
  static final messages =
      obx.QueryBacklinkToMany<ChatMessageEntity, ChatSession>(
        ChatMessageEntity_.session,
      );
}
